# Generated by Django 5.0.2 on 2024-02-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_person_latitude_person_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="kadastr_image",
            field=models.ImageField(default=1, upload_to="kadastr_images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="passport_image",
            field=models.ImageField(default=1, upload_to="passport_images/"),
            preserve_default=False,
        ),
    ]
