# Generated by Django 5.0.2 on 2024-02-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_person_kadastr_image_person_passport_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="passport_secondary_image",
            field=models.ImageField(default=1, upload_to="passport_images/"),
            preserve_default=False,
        ),
    ]
