# Generated by Django 5.0.2 on 2024-02-28 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_person_passport_secondary_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                "verbose_name": "Ta'rif",
                "verbose_name_plural": "Ta'riflar",
                "db_table": "subscription_plans",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlanUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.person"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ta'rifga obuna bo'lgan shaxs",
                "verbose_name_plural": "Ta'rifga obuna bo'lgan shaxslar",
                "db_table": "subscription_plan_users",
                "unique_together": {("user", "plan")},
            },
        ),
    ]
