# Generated by Django 5.0.2 on 2024-02-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_subscriptionplan_subscriptionplanuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplanuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
