# Generated by Django 5.0.2 on 2024-03-02 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_passportimage_remove_person_passport_secondary_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="passport_image",
        ),
        migrations.AddField(
            model_name="passportimage",
            name="person",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passport_images",
                to="main.person",
            ),
            preserve_default=False,
        ),
    ]
