# Generated by Django 5.0.2 on 2024-03-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_remove_person_passport_image_passportimage_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="passport",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
